### PR TITLE
Change UI for TripView + yellow AccentColor

### PR DESCRIPTION
**Pull request by DragonCat4012**
Draft!!! code needs maybe some refactoring so its a wip

# Motivation
added a more simple tripview which is extendable to show more details. why less information? bc its easier to first decide for a trip based on the time and transportation types and then to review the trip details. before it was very overwhleming having that many information on the screen for the user to read and sort out.

Also madesome changes regarding Colors and textStyle in the extended Form to make it easier for the user to directly spot important infomation.

Added a yellow acceent color since blue doesnt fit the yello colorsheme of the app-logo and the brand.

added a shortname function to further reduce information overflow in the tripView

# Gitignore
Additionally added some files to the gitignore

# Showcase
tripView

tripDetailView

### CODE REVIEW

**Comment by t0mbrn** [comment]
will the new trip view include the ability to start a live activity for a sub trip?

**Comment by Hanashi** [comment]
> will the new trip view include the ability to start a live activity for a sub trip?

Not for now, but we can gladly plan this for the future.

**Comment by t0mbrn** [comment]
Maybe use sf-symbol "stairs" with the arrow in the top bar to make it more clear what's meant?

**Comment by DragonCat4012** [comment]
> Maybe use sf-symbol "stairs" together with the arrow in the top bar to make it more clear what's meant?

there not enough space to make two icons next to each other, im thinking of not showing the stairs in the bar at all since for most people its not an important informatkion and in the trip detail view theyre visible

**Comment by t0mbrn** [comment]
> > Maybe use sf-symbol "stairs" together with the arrow in the top bar to make it more clear what's meant?
> 
> 
> 
> there not enough space to make two icons next to each other, im thinking of not showing the stairs in the bar at all since for most people its not an important informatkion and in the trip detail view theyre visible

Or maybe create a custom symbol? SF Stairs with an arrow?
Idk just an idea

**Comment by Hanashi** [comment]
Hi it's currently a draft, so I changed it to draft :)
I will comment in the next days to your changes. But currently it looks very good :)

**Comment by DragonCat4012** [comment]
oh yea sry meant do to that but forgot ^^"

**Comment by DragonCat4012** [comment]
> > > Maybe use sf-symbol "stairs" together with the arrow in the top bar to make it more clear what's meant?
> > 
> > 
> > there not enough space to make two icons next to each other, im thinking of not showing the stairs in the bar at all since for most people its not an important informatkion and in the trip detail view theyre visible
> 
> Or maybe create a custom symbol? SF Stairs with an arrow? Idk just an idea

hm sf only has stairs upwards so idk, I will probably just remove the stair icon in the bar view

**Comment by Hanashi** [comment]
Hello, the code looks good. I will test it and then approve it. I'll get to it sometime this week :)

**Review by Hanashi — APPROVED** [review]

**Pull request merged**
